# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20160920_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
