# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20160920_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alerts.Entity'),
            preserve_default=False,
        ),
    ]
