# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alert_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
