# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20161109_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='code',
            field=models.CharField(default=479295599292744532829924, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
