# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_entity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='id',
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
